spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch_guide
    username: root
    password: 1234

  batch:
    jdbc:
      initialize-schema: always
